### ISSUE TITLE
Getting `API token is invalid` for reads but writing works

### ISSUE THREAD

**Issue by qodesmith** [makenotion/notion-sdk-js#436] opened 2023-08-09 18:14 UTC
**Describe the bug**
I am able to write to a database but unable to read from it. `notion.pages.create(...)` works fine but `notion.databases.query(...)` throws the following error:

```
APIResponseError: API token is invalid.
```

I am using the same integration secret and database ID for both `create` and `query`.  I also have all permissions checked on the integration.

**To Reproduce**
Node version: Node.js v20.0.0
Notion JS library version: `^2.2.10`

```javascript
const notion = new Client({auth: MY_INTEGRATION_SECRET})
const response = await notion.databases.query({database_id: MY_DATABASE_ID})
console.log(response)
```

**Additional context**
Here's the error output in the console:
```text
@notionhq/client warn: request fail { code: 'unauthorized', message: 'API token is invalid.' }
/Users/qodesmith/repos/notion-bible/node_modules/@notionhq/client/build/src/errors.js:162
        return new APIResponseError({
               ^

APIResponseError: API token is invalid.
    at buildRequestError (/Users/qodesmith/repos/notion-bible/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/Users/qodesmith/repos/notion-bible/node_modules/@notionhq/client/build/src/Client.js:347:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/qodesmith/repos/notion-bible/query.js:5:18 {
  code: 'unauthorized',
  status: 401,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [ 'Wed, 09 Aug 2023 18:06:15 GMT' ],
      'content-type': [ 'application/json; charset=utf-8' ],
      'content-length': [ '87' ],
      connection: [ 'close' ],
      'x-powered-by': [ 'Express' ],
      etag: [ 'W/"57-QCRLT3IovYEW+CkwyJQlFtiXiG8"' ],
      vary: [ 'Accept-Encoding' ],
      'cf-cache-status': [ 'DYNAMIC' ],
      'set-cookie': [
        '__cf_bm=33mACEOrIyHVjdW1eHWsSVHZfYmiAOGzlESz7OpVySM-1691604375-0-ATO1AawyUNzwJqjNYT1up01x2kroCltKDcExfueFAhOxy+O7/rQ60ChMbZLm5S2XdNtiJua1C/2HtIxYpZ8FPHk=; path=/; expires=Wed, 09-Aug-23 18:36:15 GMT; domain=.notion.com; HttpOnly; Secure; SameSite=None'
      ],
      server: [ 'cloudflare' ],
      'cf-ray': [ '7f41ee94c963425c-EWR' ]
    }
  },
  body: '{"object":"error","status":401,"code":"unauthorized","message":"API token is invalid."}'
}
```

**Comment by rhart92** [comment] 2023-08-11 19:56
Closing this issue as the issue is actively being debugged through Notion customer support.

**Closed by rhart92** 2023-08-11 19:56 UTC
