### ISSUE TITLE
Select color property disregarded

### ISSUE THREAD

**Issue by csholmq** [makenotion/notion-sdk-js#192] opened 2021-09-15 21:24 UTC
When creating a page in a database the `color` property doesn't seem to take effect.

![image](https://user-images.githubusercontent.com/1297882/133511659-cf78052e-e2c7-4d23-8246-ffb9f1ff7240.png)

```
create: async (name: string, url: string, id: number, state: string) => {
			try {
				let response = await notion.pages.create({
					parent: {
						database_id: database_id
					},
					properties: {
						//@ts-ignore
						Name: {
							title: [
								{ text: { content: name }, type: 'text' }
							]
						},
						//@ts-ignore
						'URL': {
							url: url
						},
						// @ts-ignore
						id: {
							number: id
						},
						state: {
							//@ts-ignore
							select: {
								name: state,
								color: (state === 'open')? 'green':'red'
							}
						}
					}
				})

				if (response) return "✔ page created";
			} catch (error) {
				throw error;
			}
		},
```

**Comment by cwang314** [comment] 2022-02-02 23:05
Hi @csholmq, thanks for the report and sorry for the delayed response. This is actually expected behavior; because select color is a database-wide attribute, we felt that it wouldn't make sense to be able to change it for the entire database when adding/updating a page. 

I'm closing this issue because we want issues in this repo to be related to the SDK specifically, not to the API as a whole. You can submit bugs and feature requests for the API through Intercom by going to https://developers.notion.com/ and clicking "Help" in the footer.

**Closed by cwang314** 2022-02-02 23:05 UTC
Labels: enhancement, api

**Comment by laripereira14** [comment] 2022-07-26 23:28
Sorry if here is not the correct place to ask this, but how can I set all the values of a property to be the same color if the color property doesn't take effect? What is it for if it's being ignored? I'm a bit confused. Thanks!
