### ISSUE TITLE
Childrens for toggle blocks when assign and pass to the api are not created. 

### ISSUE THREAD

**Issue by a2pr** [makenotion/notion-sdk-js#140] opened 2021-07-04 17:09 UTC
Versions:
nodejs: v14.17

### code
```
content = await notionClient.blocks.children.list({
        block_id: pageId,
        page_size: 50,
    });

for(const block of content){
  if(block.type === "toggle"){
     block.children = await  await notionClient.blocks.children.list({
        block_id: blockId
    });
  }
}
``` 
When then creating the page with the content as children.  It doesnt create the page with the toggle populated with the complete content. 

## Photo of the template used to pass information
- ![Photo of the template used to pass information](https://user-images.githubusercontent.com/21030383/124393462-a4b7a200-dcc8-11eb-836e-7a86c7c5f377.png)

## Photo of created page
- ![Photo of created page](https://user-images.githubusercontent.com/21030383/124393485-bf8a1680-dcc8-11eb-949b-47210ef886a5.png)

**Comment by cwang314** [comment] 2022-02-03 19:44
Hey @a2pr, fyi - `blocks.children.list` only reads block children and does not write the children back. You need to use the [append block children endpoint](https://developers.notion.com/reference/patch-block-children) to add children to the toggle block.

Closing because this is expected behavior, and because it's not a bug with the SDK specifically.

**Closed by cwang314** 2022-02-03 19:44 UTC
Labels: api
