### ISSUE TITLE
Can't create page / image url lost when appending block image element with type 'file' instead of 'external'

### ISSUE THREAD

**Issue by stillnaughty** [makenotion/notion-sdk-js#410] opened 2023-06-21 00:51 UTC
**Scenario**
- I used 'Save to Notion' chrome plugin to save article to a 'To Read' database.
- When finish reading if it's worth saving to my 'Note Library' i will check the checkbox of that article page
- The bot will run in regular interval to check for the checked status, create a new page on 'Note Library', and archive the corresponding page on 'To Read' database.

**Situation**

On the image block element, by the chrome plugin default, the block is specified as a 'file' type instead of 'external' type

**Result**

1. Page cannot be created, as validation error occurs on image block elements
```
@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'body failed validation: body.children[0].image.external should be defined, instead was `undefined`.'
}
```

2. the bot try to change the block image element data to 'external' type instead of 'file' type, by specifying image as:
```
...
// image: {
//   type: 'file',
//   file: {
//       url: https://s3.us-west-2.amazonaws.com/secure.notion-static.com/xxxxxxx,
//       expiry_time: xxxxx,
//   },
// }

image: {
  type: 'external',
  external: { url: https://s3.us-west-2.amazonaws.com/secure.notion-static.com/xxxxxxx }, // image.file.url
}
```
However in this case, the image block element on the new created page is `{ caption:[] }`.  No image url is specified.

I do need the `pages.create()` & `blocks.children.append()` to support image type 'file' (not 'external'), or have a workaround with it.

Thank you 🙇🏻‍♂️

**Comment by rhart92** [comment] 2023-06-27 19:19
Hey @stillnaughty. I'm not 100% sure I follow what you're trying to do but it sounds like the issue is related to file upload which isn't supported by the Notion public API at the moment. 

To try to help a bit, the `type: "file"` is reserved for files that have been uploaded to Notion. To create pages with custom images via the public API, you'll have to download the image using the URL provided by the `retrievePage` API, upload the image to your file host (e.g. AWS S3), then use `type: "external"` and provide the URL to the image on your file host. ([relevant docs](https://developers.notion.com/reference/file-object))

Since issues on this repository are meant to be specific to the JS SDK not the API I'm going to close this for now. If you'd like to file a feature request for the API, please contact customer support through the Notion app 🙏

**Closed by rhart92** 2023-06-27 19:19 UTC

**Comment by stillnaughty** [comment] 2023-06-28 17:59
@rhart92
No that's not the case

I want to duplicate a page which have an uploaded image in it.
No way to do so
