### ISSUE TITLE
transclusion_container blocks not returned in blocks.children.list

### ISSUE THREAD

**Issue by transitive-bullshit** [makenotion/notion-sdk-js#283] opened 2022-04-03 14:22 UTC
**Describe the bug**

`transclusion_container` blocks are not returned as children in `blocks.children.list`.

**To Reproduce**
Node version: 16
Notion JS library version: 1.0.4

Using the public notion kit test suite: https://notion.so/067dd719a912471ea9a3ac10710e7fdf

```ts
client.blocks.children.list({ block_id: '067dd719-a912-471e-a9a3-ac10710e7fdf' })
```

It returns the following child blocks:

```ts
          "572fcaf2-d9d0-45c4-abcc-1b0aaf4fccb8",
          "5d9e09be-0391-4357-b615-5dde6897aab9",
          "6bad7d71-3fdd-4e42-bfcb-56f691b2175d",
          "aa69255b-583a-46c1-a14c-260f74320d36",
          "2db237ad-23fa-4b91-9a36-affec9a9b6d7",
          "7298a3e0-34bd-45e0-ae81-278236ef2e83",
          "31f5b12f-835d-40a1-965a-1a8984f53571",
          "c6b8e232-f65b-4b53-b01f-86d14cd420ab",
          "5bb0b0e2-d2fe-40dc-a499-afa97f9515f1",
          "1d956261-5a80-4f76-adf9-bf098dc9bfcd",
          "113837aa-25eb-4bbb-9750-b858f286af6a",
          "ab8cbfa3-787a-490d-bd53-54d77c717d5f",
          "248ce503-9770-42f4-b9fd-9b396ce76692"
```

**Expected behavior**

It skips right over the block `"154ee1b6-887d-4408-b198-e88337a9aefe"`. This is the `transclusion_container` block at the footer of the test suite page.

**Additional context**

This is the first of likely many bug reports as I work on an OSS [compatibility layer](https://github.com/NotionX/react-notion-x/pull/256) between the official and unofficial notion APIs. The goal is to be able to render notion page content faithfully like the official notion renderer does.

**Comment by rhart92** [comment] 2022-05-13 19:56
Thanks for the report @transitive-bullshit. I tried to replicate your issue but I was able to fetch `transclusion_container` blocks via the `blocks.children.list` endpoint successfully. After inspecting the block you reference, it seems like somehow the `transclusion_container` that isn't being returned is missing a `created_at` and `last_edited_time` values which usually occurs when using the private API to update Notion blocks. To resolve this issue, you'll have to re-create the block via the UI and then you'll be able to fetch it via the API. If you want to test this for yourself, just create a new synced block in the UI and try to fetch it via the API and you should see that it works as expected. Closing this issue since it's not reproducible outside of this particular block which appears to be malformed.

**Closed by rhart92** 2022-05-13 19:56 UTC
Labels: bug

**Comment by transitive-bullshit** [comment] 2022-05-13 20:04
Interesting; I've never used the private API for write access.

Anyhow, thanks for the detailed response 🙏
