### ISSUE TITLE
Database query results are missing metadata from properties

### ISSUE THREAD

**Issue by Amber-Williams** [makenotion/notion-sdk-js#317] opened 2022-07-11 22:34 UTC
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.

**Describe the bug**
Currently the SDK doesn't give much outside of an id in the property. Equivalent request in Postman, has detailed JSON with `id`, `type` and content. 

**To Reproduce**
Node version: `v16.14.2`
Notion JS library version: `v2.0.0`

```
const { Client } = require("@notionhq/client");

const notion = new Client({
  auth: process.env.NOTION_API_KEY
});

(async () => {
  const databaseId = process.env.NOTION_DATABASE_ID;
  const response = await notion.databases.query({
    database_id: databaseId,
    filter: {
      property: "Tags",
      multi_select: {
        contains: "italian",
      },
    },
  });

  console.log(response.results[0].properties);
  console.log(response.results[1].properties);

  process.exit();
})();

```

**Expected behavior**
Content inside database item properties

**Screenshots**
<img width="714" alt="image" src="https://user-images.githubusercontent.com/27780374/178368436-4dc02e64-a08a-4aa0-b2bf-6d8804a13978.png">

**Comment by pnome** [comment] 2022-07-12 15:17
I thought this was a bug too, but it looks like it's intended behaviour - [https://developers.notion.com/changelog/releasing-notion-version-2022-06-28](https://developers.notion.com/changelog/releasing-notion-version-2022-06-28)

I can see why they did it, but it makes it very frustrating when I want to quickly pull property info from a number of pages at the same time.

**Comment by Amber-Williams** [comment] 2022-07-12 16:36
@pnome This is a database query vs page query and the equivalent Notion `curl` commands yield what is stated from the Notion API docs

**Comment by pnome** [comment] 2022-07-12 17:05
@Amber-Williams I'm not sure what you mean.

All I know is that prior to the most recent API update I could query a database (like you show in your code example) and I'd get all of the property details.  E.g. if I had a select property, I'd see `type: select` followed by `select : {  all the select property info }`

In the most recent version all you get is what you showed. I've been pulling my hair out for hours trying to figure out why it had disappeared, but the ChangeLog says it's intentionally stripped out and you have to make requests to the pages to get property info. The reason being that it was giving timeouts if there was too much info in a page.

If you're comparing to curl or postman, just check which version of the API is being used.

`  -H 'Notion-Version: 2022-06-28' \` gives the same results as the 2.0.0 SDK

**Comment by Loque18** [comment] 2022-07-14 17:37
```
const getEntries = async () => {
    const { results } = await notion.databases.query({ database_id: databaseId});

    const property_id = results[0].properties['PROPERTY_NAME'].id;

    const propValues = results.map(async res => {
        const { id: page_id } = res;

        const props = await notion.pages.properties.retrieve({
            page_id,
            property_id,
        });

        return prop .number;
    });

    return Promise.all(props);
};

(async () => {
    const res = await getEntries();

    console.log(res);
})();
```

**Comment by xoxohorses** [comment] 2022-07-14 23:01
Hi @Amber-Williams, thanks for opening this issue. What you are seeing is expected behavior as explained by @pnome and @Loque18 (thanks both) and you can find more details about the thought process behind it in our [changelog](https://developers.notion.com/changelog/releasing-notion-version-2022-06-28).

You can also find an example of how to use this new endpoint in our sample integration [Sync Notion with Github Issues](https://github.com/makenotion/notion-sdk-js/blob/d99555bea8386b6a913f5b3ed6188b0a4c7781f6/examples/database-email-update/index.js#L168-L193).

If you have any additional questions, please email us at developers@makenotion.com. Closing this out

**Closed by xoxohorses** 2022-07-14 23:01 UTC

**Comment by e-e-e** [comment] 2022-07-31 11:25
Is there any way to fetch properties in bulk?
If not then this change is not ideal for any use case that requires properties from multiple rows - it multiplies the number of requests that a consumer needs to make by the number of rows. For a database with 10 items, a consumer needs 11 api calls to fetch all properties that they require. Given the api is already heavily rate limited this seems really prohibitive - 3 requests per second.

**Comment by dylanyoung-dev** [comment] 2022-07-31 22:47
Yeah I get improving the performance of the initial page request call, but as @e-e-e mentions above, this makes this whole API inefficient and almost unusable.  I will continue to use an old API Version and older client until this is resolved, or I may have to find another tool to use.  The bulk option would be a good compromise, but still would require 1 additional request per page.  Maybe having an option to include full responses for specified props on the main query would be a better way.  So as a developer you can opt to pull the fields you need, but not the ones you don't need.

**Comment by e-e-e** [comment] 2022-08-01 04:16
Oh - its actually much worse than I thought - now playing a bit more with the API, I notice that you have to make 1 additional request per property that you would like to access. So if I have a database query which returns 10 items, each with 5 extra properties that I would like to read. With this new api I have to make 10 * 5 + 1 (51) requests to fetch all the data from the query. This not very optimal. 

@Amber-Williams is there any alternative?

**Comment by MonstraG** [comment] 2022-08-01 18:22
Yeaa, I've been fetching one table that has 64 rows and 6 properties, and this change just made 1 call into, it seems, 385 (64 * 6 +1), where (64 * 5) of them are just boolean values for checkboxes.

**Comment by lavgup** [comment] 2022-08-02 07:40
Agreed, being able to get all the properties for a page in a single request is a far better compromise then sending a request for _every_ property on the page.

**Comment by Amber-Williams** [comment] 2022-08-15 20:48
@e-e-e I opted in to regress the API version on the row page retrieval as so
```
const fetchRowData = async ({ id }) => {
  const response = await fetch(`https://api.notion.com/v1/pages/${id}`, {
    headers: {
      Authorization: `Bearer ${process.env.NOTION_API_KEY}`,
      "Notion-Version": "2022-02-22",
    },
  });

  return response.json();
};

(async () => {
  try {
    const { results } = await notion.databases.query({
      database_id: process.env.NOTION_DATABASE_ID,
      filter: {
        property: "Tags",
        multi_select: {
          contains: CONTAINS_TAG,
        },
      },
    });

    const databaseRowPromises = results.map(async ({ id }) => {
      const rowData = await fetchRowData({ id });
      return {
        content: rowData.properties.content,
      };
    });

    const data = await Promise.all(databaseRowPromises);

    return data;
  } catch (error) {
    // handle error
  }
})();
```

That version will be phased out eventually and very well may stay like this due to Notion's use of nested pages and rollups in databases. In which case, the best solution I can think of is to batch fetch rows, cache them, and attempt to keep your cache in sync if/when your app makes updates. Also would need to make use of the `GET` database's `last_edited_by` to check if you need to re-fetch the database in instances it isn't your token's bot id. Would be interested to learn how Notion's team recommends to best use the latest version
