### ISSUE TITLE
GetPageResponse missing properties typing

### ISSUE THREAD

**Issue by soullivaneuh** [makenotion/notion-sdk-js#302] opened 2022-05-24 12:00 UTC
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.

**Describe the bug**
The `notion.pages.retrieve` method returns a page object with the following data:

```
Success:  {
  object: 'page',
  id: 'xxx',
  created_time: '2021-01-18T17:43:00.000Z',
  last_edited_time: '2022-05-24T11:25:00.000Z',
  created_by: { object: 'user', id: 'xxx' },
  last_edited_by: { object: 'user', id: 'xxx' },
  cover: null,
  icon: { type: 'emoji', emoji: '👨‍💻' },
  parent: { type: 'workspace', workspace: true },
  archived: false,
  properties: { title: { id: 'title', type: 'title', title: [Array] } },
  url: 'https://www.notion.so/xxx'
}
```

However, only the `id` and `object` properties are available according to Typescript.

Possibly related to #219 and #288.

**To Reproduce**
Node version: v18.2.0
Notion JS library version: v1.0.4

Code snippet:

```typescript
import {
  Client,
} from '@notionhq/client';

const notion = new Client({
  auth: process.env.NOTION_API_KEY,
});
const pageId = 'xxx';
notion.pages.retrieve({ page_id: pageId })
  .then((result) => {
    result.id
    console.debug('Success: ', result.cover);
  })
  .catch((err) => {
    console.error('Failed: ', err);
  })
;
```

**Expected behavior**

Working script.

**Current behavior**

```
error TS2339: Property 'cover' does not exist on type 'GetPageResponse'.
  Property 'cover' does not exist on type '{ object: "page"; id: string; }'.

15     console.debug('Success: ', result.cover);
                                         ~~~~~
```

**Comment by cwang314** [comment] 2022-05-27 23:05
Duplicate of https://github.com/makenotion/notion-sdk-js/issues/288

**Closed by cwang314** 2022-05-27 23:05 UTC

**Comment by navaru** [comment] 2022-12-24 03:42
This is still an issue on v2.2:

```
Property 'cover' does not exist on type 'GetPageResponse'.
  Property 'cover' does not exist on type 'PartialPageObjectResponse'.
```
