### ISSUE TITLE
Databases result objects have invalid ids 

### ISSUE THREAD

**Issue by ZeroPie** [makenotion/notion-sdk-js#153] opened 2021-07-17 12:51 UTC
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@notion.com.

**Describe the bug**
if i fetch my databases through https://api.notion.com/v1/databases
i get invalid ids (separated through - )

```
{
  "object": "list",
  "results": [
    {
      "object": "database",
      "id": "8154ca77-0c6a-4191-adb7-28273265c28a",
      "created_time": "2021-07-16T21:42:00.000Z",
      "last_edited_time": "2021-07-16T21:44:00.000Z",
      "title": [
```

**To Reproduce**
Node version: v14.15.1
Notion JS library version: ^0.2.2

fetch databases from https://api.notion.com/v1/databases
use id

```

const data = await notion.databases.query({
    database_id: "8154ca77-0c6a-4191-adb7-28273265c28a",
})

///
body: '{"object":"error","status":400,"code":"validation_error","message":"path failed validation: path.databaseId should be a valid uuid, instead was `\\"8154ca77-0c6a-4191-adb7-28273265c28\\"`."}'
```

the correct id would be
```
const data = await notion.databases.query({
    database_id: "8154ca770c6a4191adb728273265c28a,
})
```

**Expected behavior**
Some Ideas:
- ids are returned with proper formatting
- the sdk can accept those ids
- or the sdk will trim the -'s
- or the sdk documentation has info about this :)

**Screenshots**
Please include any screenshots that help explain your problem.

**Additional context**

**Comment by alfonsodlopez** [comment] 2021-07-23 07:27
Please run the following CURL command in the terminal, using your bot token, and let us know if you receive a valid response.

```
curl --location --request POST 'https://api.notion.com/v1/databases/8154ca77-0c6a-4191-adb7-28273265c28/query' \
--header 'Content-Type: application/json' \
--header 'Notion-Version: 2021-05-13' \
--header 'Authorization: Bearer YOUR_BOT_TOKE' \
--data ''
```

**Comment by cwang314** [comment] 2022-02-02 22:55
Closing because this is expected behavior. For future reference, we'd like issues in this repo to be related to the SDK specifically, whereas this issue appears to be related to the API.

**Closed by cwang314** 2022-02-02 22:55 UTC
Labels: api
