### ISSUE TITLE
Search API endpoint is not working

### ISSUE THREAD

**Issue by ru-web-designer** [makenotion/notion-sdk-js#278] opened 2022-03-21 15:30 UTC
I tried to use search API endpoint as it described here https://developers.notion.com/reference/post-search and always got empty list object as a result:
![image](https://user-images.githubusercontent.com/3310192/159292750-99429085-8dca-4542-968b-521d1df76a4c.png)

Demo: https://github.com/ru-web-designer/notion-search-api-issue

**To Reproduce**
Node version: 16.14.0
Notion JS library version: 1.0.4

**Expected behavior**
By passing a request body like this:
```js
{
  query: "test",
  page_size: 100
}
```
I expect to get all databases and pages with a title containing "test" string. To view the whole code, visit my demo repository, dedicated to this issue https://github.com/ru-web-designer/notion-search-api-issue

**Screenshots**
The code:
![image](https://user-images.githubusercontent.com/3310192/159294937-968e2382-d022-4ed1-81ab-cb3963b410bd.png)

Integration capabilities:
![image](https://user-images.githubusercontent.com/3310192/159294194-63754047-a076-4b78-9154-99e69095807b.png)

Result:
![image](https://user-images.githubusercontent.com/3310192/159294232-b965b5eb-4a8d-47fa-b963-990ff306535b.png)

For quick reproduction clone my dedicated repo with full source code https://github.com/ru-web-designer/notion-search-api-issue

**Additional context**
I tried both @notionhq/client and Axios example from the documentation page https://developers.notion.com/reference/post-search They both failed with the same result. So maybe this issue should be reported to the API's repo.

**Comment by glade-at-gigwell** [comment] 2022-04-02 19:12
I'm having the same issue.  Even with a completely empty search, and full permissions, the search result is always empty.

**Comment by ru-web-designer** [comment] 2022-04-19 20:49
> I'm having the same issue. Even with a completely empty search, and full permissions, the search result is always empty.
> 
> (edit) I figured it out. You need to Invite the Integration user to the Workspace before it can see any of the pages.

I did integration with user that owns the workspace, so It won't work for me :(

**Comment by david-jng** [comment] 2022-05-11 19:24
I am able to reproduce this issue using request-promise.

`const request = require("request-promise")`

![image](https://user-images.githubusercontent.com/41423063/167929373-6dd55022-7fe0-4af0-810e-53dcbfe1979b.png)

![image](https://user-images.githubusercontent.com/41423063/167929624-59c212a4-f5b5-4c08-ad3b-401f3c989ce9.png)

My bot has the same capabilities as @ru-web-designer has shown.

**Comment by rhart92** [comment] 2022-05-13 19:10
As this issue seems to be more related to specific issues with search rather than the JS SDK I'm going to close this issue. Please contact Notion support via the Notion UI for specific assistance related to API issues. Usually these issues are resolved by what @glade-at-gigwell mentioned of making sure to share pages with the bot as by default a bot has access to nothing in the workspace regardless of what is selected in the `Capabilities` section when creating the bot.

**Closed by rhart92** 2022-05-13 19:10 UTC
Labels: api

**Comment by terwer** [comment] 2023-08-04 06:10
search return empty

```
curl --location 'https://api.notion.com/v1/search' \
--header 'Notion-Version: 2022-06-28' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer secret_xxx' \
--data '{}'
```
