### ISSUE TITLE
Title column of a table cannot be fetched or inserted

### ISSUE THREAD

**Issue by bambooom** [makenotion/notion-sdk-js#277] opened 2022-03-18 16:56 UTC
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.

**Describe the bug**
When I query a database's entries, I cannot get the value of Title-typed column, but it's shown on website.
And when I want to create a page for this database, the title column's value also cannot be inserted.

**To Reproduce**
Node version: v16.14.0
Notion JS library version: 1.0.3

```js
const {Client} = require("@notionhq/client");
const notion = new Client({
  auth: process.env.NOTION_TOKEN,
});
(async () => {
  const data = await notion.databases.query({
    database_id: process.env.DBID,
    sorts: [
      {
        property: '打分日期',
        direction: 'descending',
      },
    ],
  });

  console.log(JSON.stringify(data.results[3], null, 2));
})();

```

run this simple script on [my database](https://bambooo.notion.site/db9d1ab42f49420fb14aedf930388997?v=88de37ee3b2e4b6998b5c46ebb328ba9) like this:
![Screen Shot 2022-03-19 at 12 51 12 AM](https://user-images.githubusercontent.com/14840170/159047272-24999646-f60a-45d7-a47e-0ed29a57c228.png)

I suppose to log out the details of the 4th row, it has value in the Title column, which I named as just 'Name'.
But the log is like:

```
    "打分日期": {
      "id": "yxCh",
      "type": "date",
      "date": {
        "start": "2022-03-13",
        "end": null,
        "time_zone": null
      }
    },
    "Name": {
      "id": "title",
      "type": "title",
      "title": []
    },
    "上映年份": {
      "id": "56458379-82fd-4d14-8864-4b9b1a09430d",
      "type": "number",
      "number": 2021
    },
    "类型": {
      "id": "6f659568-32d5-4fad-8e00-5972760cf2d5",
      "type": "multi_select",
      "multi_select": [
.....
```

The `Name` properties with `type: title` does not have any value here.

**Expected behavior**
`Name` properties should have the value which is already shown on notion website.

**Screenshots**
![Screen Shot 2022-03-19 at 12 42 39 AM](https://user-images.githubusercontent.com/14840170/159047844-38e6e026-7cce-4fa8-83b1-1288160aec6d.png)

**Additional context**
Also I'd like to create more pages(rows) for this database, all rows's title-typed 'Name' column missing without any error reported.

**Comment by rhart92** [comment] 2022-05-09 18:46
Hi @bambooom, looks like the `Name` property is empty in this case because there is no title for this row in the database ([link](https://bambooo.notion.site/e18067ecca7342e3a19a63ac45dca8de) to the referenced row in your database) The title shows the placeholder text `Untitled` which the API won't return which is why you are getting an empty array as the value. In the view you have pasted, the icon is the page icon which isn't part of the title.

Since this doesn't seem to be a problem with the API client, I'm going to close this but hope this helps 🙏 

Related to the additional context, when creating / updating pages in the database the Notion API doesn't validate that pages have a title (or any other property) by design when being created in a database. This allows for flexibility if users want to create pages without filling in all properties.

**Closed by rhart92** 2022-05-09 18:46 UTC
Labels: api

**Comment by bambooom** [comment] 2022-05-10 02:23
@rhart92  Hi, thanks for your reply. But the link you provided is not what I'm quoting. 
The screenshot I provided is corresponding another page, https://bambooo.notion.site/Spider-Man-No-Way-Home-e29290adbbeb4d8d826ae09dc392f541. 
This one does have "Title" as I said, so what you said does not make sense. 
Please re-open this issue.
