### ISSUE TITLE
error: whatwg-ur does not provide export default

### ISSUE THREAD

**Issue by silveltman** [makenotion/notion-sdk-js#389] opened 2023-03-04 20:37 UTC
error:
```
Uncaught (in promise) SyntaxError: The requested module '/node_modules/whatwg-url/lib/public-api.js?v=e36404ad' does not provide an export named 'default' (at index.mjs?v=e36404ad:4:8)
```

Svelte component:
```
<script>
  import { Client } from '@notionhq/client'
</script>
```

Astro page:
```
---
import Test from '@components/Test.svelte'
---

<Test client:load />
```

Node version: 16.15.1
Notion JS library version: 2.2.3

Trying to find a solution for a long time, no results :(

**Comment by rhart92** [comment] 2023-03-08 01:48
Hello @silveltman. Based on details you've given I'm not 100% sure what the issue is but something I did notice is that you are trying to use the Notion `Client` inside the `Svelte` component which may cause issues since that is client side code. My recommendation is to move the data fetching from Notion to the front-matter section in the `Astro` page. Once you have fetched the data from Notion, you should be able to pass the it as props to your Svelte components. I have provided some example code that I was able to get running on the latest version of Astro + Notion Client and should be extendible to your use case 🙏 

```astro
---
// Fetch the data from Notion in the Astro frontmatter
import { Client } from "@notionhq/client"

const notion = new Client({
  auth: <INSERT_AUTH_TOKEN>,
  fetch: fetch
})

// Example of fetching Users
const users = await notion.users.list({})
---

<pre>{JSON.stringify(response2, null, 2)}</pre>
```

I'm going to close this issue as it doesn't seem like a bug with the Notion SDK. Good luck!

**Closed by rhart92** 2023-03-08 01:48 UTC

**Comment by silveltman** [comment] 2023-03-08 19:14
Thanks @rhart92. However, we purposefully put this code client-side because we need live data for this particular component. 

I think our solution for now is witching our Astro project to SSR, or at least this part of the app with Hybrid rendering. 

Thanks again!
