### ISSUE TITLE
Facing issue while calling notion API through serverless framework

### ISSUE THREAD

**Issue by rtpatil** [makenotion/notion-sdk-js#128] opened 2021-06-25 03:29 UTC
facing an issue while calling an notion API with my "serverless" and "serverless-offline" framework when running a API getting an below error as,

getting issue when calling a method,

auth:'secret_UjR5Ta6Y08zYmIvGoTY2XJVfUUSDdAaASh78rWxxaNF'
database_id = '9a972ddf-dbb5-4877-a87e-35d7aa584cf3';

const payload={
path:'databases/'+database_id+'/query',
method:'POST'
}

const {results} = await notion.request(payload);

Node 10.X :
(node:8744) UnhandledPromiseRejectionWarning: RequestError: Cannot read property 'startsWith' of undefined
at Request._makeRequest (.....\node_modules\@notionhq\client\node_modules\got\dist\source\core\index.js:1177:19)
at Request (....\node_modules\@notionhq\client\node_modules\got\dist\source\core\index.js:328:28)

**Node 12.X**
Request Error: connect ECONNREFUSED
Tried with different versions of Node 10 - 14 , also working when we are not using serverless-framework, the only issue while running with serverless-framework.

Please let us know any suggestions / supporting methodology.

Below is the package.json file for reference.

"devDependencies": {
"@notionhq/client": "^0.1.9",
"eslint": "5.16.0",
"nyc": "14.1.1",
"serverless": "1.46.1",
"serverless-mocha-plugin": "1.10.0",
"serverless-offline": "5.3.3",
}
when browsed, suggested to check with serverless framework (refer below link)

https://githubmemory.com/repo/NotionX/react-notion-x/issues/52

**Comment by t3db0t** [comment] 2021-07-20 14:19
You should _**really really not**_ include your integration key and database id

**Comment by JoarGjersund** [comment] 2021-08-11 10:15
probably blocked by CORS policy. Check out https://github.com/Rob--W/cors-anywhere . It is also really stupid to publish your auth keys . You could try fetching them from url via get instead if you want your page to be fully static.

**Comment by rhart92** [comment] 2022-02-02 23:00
Closing issue since it seems like the issue isn't directly related to the SDK.

**Closed by rhart92** 2022-02-02 23:00 UTC
Labels: bug
