### ISSUE TITLE
Can't resolve 'encoding' in Next.js

### ISSUE THREAD

**Issue by hecker** [makenotion/notion-sdk-js#393] opened 2023-03-29 13:29 UTC
When I am initialising the Notion client in my _lib/notion.ts_ with
```
const notion = new Client({
    auth: process.env.NOTION_API_KEY,
  });
```

I get the following **error / warning in my debug console**:
```
warn  - ./node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/janhecker/Development/hecker.vc/node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib'

Import trace for requested module:
./node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
./node_modules/.pnpm/@notionhq+client@2.2.3/node_modules/@notionhq/client/build/src/Client.js
./node_modules/.pnpm/@notionhq+client@2.2.3/node_modules/@notionhq/client/build/src/index.js
./lib/notion.ts
./app/(navbar)/blog/page.tsx
```

I am using Next.js + Typescript with the new app/ library.

**My versions are:**
Next.js 13.2.4
Node v18.15.0
@notionhq/client v2.2.3

I'd be glad if anyone could help me resolve this issue. 👋

**Comment by rhart92** [comment] 2023-04-11 22:29
Hey @hecker, this is just a warning and shouldn't stop you from building your project. See #365 for some suggestions regarding this issue. I'm going to close this as it's a duplicate of #365.

**Closed by rhart92** 2023-04-11 22:29 UTC
